POST http://localhost:8080/events
content-Type:  application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGVtYWlsLmNvbSIsImV4cCI6MTcyOTM2NTc4MywidXNlcklkIjoyfQ.GYHoI1anISgRnZzAu09EqI35uVFqQNGGSnp_EHbyzjc

{
    "name":"Test event 44",
    "description":"test event 44",
    "location":"A test location",
    "dateTime":"2023-10-19T14:00:00Z"

}