POST http://localhost:8080/events
content-Type:  application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQGVtYWlsLmNvbSIsImV4cCI6MTcyOTM2MjkwMywidXNlcklkIjowfQ.a3Z-rl7utZBHxvIzV-NkpgGDC2xZ65600_tVjFL1tLU

{
    "name":"Test event 2",
    "description":"Another test event",
    "location":"A test location",
    "dateTime":"2023-10-19T14:00:00Z"

}